### ISSUE TITLE
Clicking links gives no result in Chrome 61

### ISSUE THREAD

**Issue by caramgardner** [flesler/jquery.localScroll#38] opened 2017-09-25 10:16 UTC
Links that were working as expected in previous Chrome versions - with smooth scrolling to the target - are now failing to work at all; clicking them produces no result.

**Comment by flesler** [comment] 2017-09-25 21:05
Please try updating localScroll and scrollTo to the latest version and see if it works then

**Comment by mariommoreno** [comment] 2017-09-26 20:38
Same problem here with version 1.2.7. Be ready for more cases because that version is included in some WP themes. Waiting the designer to fix/update.

**Comment by luk-bosk** [comment] 2017-09-28 21:06
I tried to upgrade to the latest version, this didn't solve the issue. 
Do you plan to provide a fix for that? Thanks!

**Comment by flesler** [comment] 2017-09-29 13:41
I updated [localScroll's demo site](http://demos.flesler.com/jquery/localScroll/) to use the latest version of both scrollTo and localScroll, it's still working correctly so it's not broken across the board for sure.

I willl need someone to be able to reproduce the issue with a small demo, if a fix is provided, even better.

**Comment by jacelevine** [comment] 2017-09-29 17:08
I was having this problem today as well with Chrome 61. I updated LocalScroll to 2.0.0 and ScrollTo to 2.1.2 and now it's working again.

**Comment by flesler** [comment] 2017-09-29 17:40
I really wonder what is that problematic in the old version (whichever it was). There hasn't been too many major changes tbh. If someone's able to actually try to pinpoint the problematic version and what's wrong with it, it would be great

**Comment by jacelevine** [comment] 2017-09-29 17:45
I can tell you that the versions I was running before were fairly old. LocalScroll 1.2.9b and ScrollTo 1.4.6. But I don't know that those versions in particular were problematic. 

No errors or messages were generated in the console during my tests. It just didn't do anything at all.

**Comment by luk-bosk** [comment] 2017-09-30 10:18
I updated also scrollTo to the latest version, all is working fine now. Thanks!

**Comment by JanKopietzGit** [comment] 2017-10-06 09:50
Hi there,
I also run into this issue with chrome. I updated to the latest version of jquery, scrollTo and localScroll. Unfortunately that didn't help. I saw the updated localScroll's demo page and there it works. The difference is, on my pages I use localScroll to scroll the browser and not content within a container. Here you can test it on a live page (header navigation):
https://www.explore-truth.com/rebecca-roberts/

Any ideas what to do?

Thanks in advance,
Jan

**Comment by AfricanTrailblazers** [comment] 2017-10-27 10:51
Funny thing. I had the same problem, but my query #24170 got closed by a member because he said github can't help with this sort of query, so I reported the bug to Chromium and they sent me back here! LOL! Anyway, I just updated from version 1.4.3.1 to your latest version and it works! So I just wanted to say THANKS! 

I also can't understand why everything was working fine before the Chrome update, and I did not understand what the Chromium guys were talking about, but maybe you can check it out and see if you can pinpoint the problem from what the Chromium guys had to say at: https://bugs.chromium.org/p/chromium/issues/detail?id=771054 

THANKS AGAIN!

**Comment by flesler** [comment] 2017-10-27 13:33
I haven't checked, but they probably messed with which of `html` and `body` needs to be used for scrolling. It's been going back and forth for years now. I stopped worrying by now :)
I improved that detection over the last version so it's probably better prepared to handle their changes than the older versions

**Closed as completed** 2018-06-07 13:51 UTC
