### ISSUE TITLE
Not scrolling in google chrome and safari

### ISSUE THREAD

**Issue by HollanderNL** [flesler/jquery.localScroll#34] opened 2017-06-29 09:53 UTC
Hello,

If I use this plugin it doesn't scroll but it just springs to the div instead of scrolling smoothly.
How to fix this?

**Comment by flesler** [comment] 2017-10-27 13:35
Probably duplicate of #38 or otherwise an error in the implementation. Feel free to reopen if you have more data

**Closed by flesler** 2017-10-27 13:35 UTC
